export const TODO_ADDED = "TODO_ADDED";
export const TODO_CHECKED = "TODO_CHECKED";
export const TODO_EDITED = "TODO_EDITED";
export const TODO_EDITED_VALUE_SUBMITTED = "TODO_EDITED_VALUE_SUBMITTED";
export const TODO_REMOVED = "TODO_REMOVED";
export const TODO_ALL_CLEARED = "TODO_ALL_CLEARED";
export const TODO_ALL_COMPLETED = "TODO_ALL_COMPLETED";
